function startOfLocalDay(value = new Date()) {
  return new Date(value.getFullYear(), value.getMonth(), value.getDate());
}

function shiftDays(base, days) {
  const next = startOfLocalDay(base);
  next.setDate(next.getDate() + days);
  return next;
}

function toLocalIso(date) {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function entry(baseDate, dayShift, payload) {
  return {
    date: toLocalIso(shiftDays(baseDate, dayShift)),
    ...payload,
  };
}

export function getMyTimeSeedEntries(now = new Date()) {
  const baseDate = startOfLocalDay(now);

  return [
    entry(baseDate, 0, {
      id: 'my-time-marc-1',
      userId: 'team_marc_pitre',
      taskTitle: 'Homepage QA sweep',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Launch QA',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      serviceTypeId: 'development',
      notes: 'Validated final responsive fixes before client review.',
      entryType: 'timer',
      startTime: '09:00',
      endTime: '10:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -1, {
      id: 'my-time-marc-2',
      userId: 'team_marc_pitre',
      taskTitle: 'Internal weekly planning',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Aligned priorities for My Time and task correction follow-up.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 45,
    }),
    entry(baseDate, -2, {
      id: 'my-time-marc-3',
      userId: 'team_marc_pitre',
      taskTitle: 'Perf tuning pass',
      jobName: 'Quantum Leap Website',
      deliverableName: 'Performance Tuning',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'development',
      notes: 'Closed image-loading regressions and cache test notes.',
      entryType: 'timer',
      startTime: '13:00',
      endTime: '15:15',
      duration_minutes: 135,
    }),
    entry(baseDate, -6, {
      id: 'my-time-marc-4',
      userId: 'team_marc_pitre',
      taskTitle: 'Stakeholder recap',
      jobName: 'Data Migration Strategy',
      deliverableName: 'Final Report Delivery',
      contextType: 'client',
      companyName: 'Legacy Corp',
      serviceTypeId: 'pm',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 75,
    }),
    entry(baseDate, -5, {
      id: 'my-time-marc-locked-1',
      userId: 'team_marc_pitre',
      taskTitle: 'Archived launch wrap-up',
      jobName: 'Legacy Launch Retrospective',
      deliverableName: 'Archive Summary',
      contextType: 'client',
      companyName: 'Legacy Corp',
      serviceTypeId: 'pm',
      notes: 'Historical entry locked after the parent work was archived.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 60,
      lockReason: 'Locked while parent work is archived.',
    }),
    entry(baseDate, -11, {
      id: 'my-time-marc-5',
      userId: 'team_marc_pitre',
      taskTitle: 'Change-order review',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Brand Guidelines',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      serviceTypeId: 'design',
      notes: 'Reviewed scope notes and consolidated open questions.',
      entryType: 'timer',
      startTime: '11:00',
      endTime: '12:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -27, {
      id: 'my-time-marc-6',
      userId: 'team_marc_pitre',
      taskTitle: 'Template cleanup',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Reworked recurring checklist copy.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 60,
    }),
    entry(baseDate, 0, {
      id: 'my-time-arthur-1',
      userId: 'team_arthur_iturres',
      taskTitle: 'Deployment verification',
      jobName: 'Quantum Leap Website',
      deliverableName: 'Frontend Deployment',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'development',
      notes: 'Confirmed production bundle and smoke-tested launch flow.',
      entryType: 'timer',
      startTime: '10:00',
      endTime: '12:00',
      duration_minutes: 120,
    }),
    entry(baseDate, -1, {
      id: 'my-time-arthur-2',
      userId: 'team_arthur_iturres',
      taskTitle: 'Internal build diagnostics',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'development',
      notes: 'Investigated dev-build latency and noted next checks.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 90,
    }),
    entry(baseDate, -3, {
      id: 'my-time-arthur-3',
      userId: 'team_arthur_iturres',
      taskTitle: 'API handoff review',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'API Integration',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      serviceTypeId: 'development',
      notes: 'Reviewed edge cases with Andres before merge.',
      entryType: 'timer',
      startTime: '14:00',
      endTime: '16:30',
      duration_minutes: 150,
    }),
    entry(baseDate, -9, {
      id: 'my-time-arthur-4',
      userId: 'team_arthur_iturres',
      taskTitle: 'Footer refactor',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Homepage Refresh',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      serviceTypeId: 'development',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 105,
    }),
    entry(baseDate, -34, {
      id: 'my-time-arthur-5',
      userId: 'team_arthur_iturres',
      taskTitle: 'Task system sync',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Checked alignment between Quick Tasks and Jobs task models.',
      entryType: 'timer',
      startTime: '15:00',
      endTime: '16:00',
      duration_minutes: 60,
    }),
    entry(baseDate, 0, {
      id: 'my-time-kumail-1',
      userId: 'team_kumail_abas',
      taskTitle: 'Proposal framing',
      jobName: 'Mobile App Revamp',
      deliverableName: 'Usability Test',
      contextType: 'client',
      companyName: 'Appify',
      serviceTypeId: 'pm',
      notes: 'Drafted summary bullets for follow-up.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 75,
    }),
    entry(baseDate, -2, {
      id: 'my-time-kumail-2',
      userId: 'team_kumail_abas',
      taskTitle: 'SEO audit review',
      jobName: 'Fathom SEO Sprint',
      deliverableName: 'SEO Audit',
      contextType: 'client',
      companyName: 'Fathom',
      serviceTypeId: 'seo',
      notes: 'Validated deliverable notes and owner summary.',
      entryType: 'timer',
      startTime: '09:30',
      endTime: '11:00',
      duration_minutes: 90,
    }),
    entry(baseDate, -8, {
      id: 'my-time-kumail-3',
      userId: 'team_kumail_abas',
      taskTitle: 'Ops cleanup',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 30,
    }),
    entry(baseDate, -31, {
      id: 'my-time-kumail-4',
      userId: 'team_kumail_abas',
      taskTitle: 'Estimate recap',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Logo Concepts',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      serviceTypeId: 'design',
      notes: 'Sent estimate summary after internal review.',
      entryType: 'timer',
      startTime: '12:00',
      endTime: '13:15',
      duration_minutes: 75,
    }),
    entry(baseDate, -4, {
      id: 'my-time-marc-7',
      userId: 'team_marc_pitre',
      taskTitle: 'Launch checklist review',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Launch QA',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      serviceTypeId: 'pm',
      notes: 'Reviewed the launch checklist with the team, confirmed remaining blockers, and noted which client-facing items still need final approval before the handoff can be shared.',
      entryType: 'timer',
      startTime: '08:30',
      endTime: '10:00',
      duration_minutes: 90,
    }),
    entry(baseDate, -4, {
      id: 'my-time-arthur-6',
      userId: 'team_arthur_iturres',
      taskTitle: 'API error-state cleanup',
      jobName: 'Quantum Leap Website',
      deliverableName: 'API Integration',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'development',
      notes: 'Cleaned up retry messaging and validated the edge cases that were causing confusing states in the staging build.',
      entryType: 'timer',
      startTime: '10:15',
      endTime: '12:45',
      duration_minutes: 150,
    }),
    entry(baseDate, -4, {
      id: 'my-time-kumail-5',
      userId: 'team_kumail_abas',
      taskTitle: 'Client SEO notes',
      jobName: 'Fathom SEO Sprint',
      deliverableName: 'SEO Audit',
      contextType: 'client',
      companyName: 'Fathom',
      serviceTypeId: 'seo',
      notes: 'Converted audit findings into client-ready notes and grouped the highest-impact fixes for the next working session.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 80,
    }),
    entry(baseDate, -5, {
      id: 'my-time-marc-8',
      userId: 'team_marc_pitre',
      taskTitle: 'Internal report QA',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Checked the Time Report filters against expected demo cases and wrote down the correction behaviors that should remain available to Owners and Admins.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 70,
    }),
    entry(baseDate, -5, {
      id: 'my-time-arthur-7',
      userId: 'team_arthur_iturres',
      taskTitle: 'Build pipeline triage',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'development',
      notes: 'Reviewed intermittent build warnings, confirmed they were unrelated to the report route, and captured follow-up notes for the shared engineering checklist.',
      entryType: 'timer',
      startTime: '15:00',
      endTime: '16:20',
      duration_minutes: 80,
    }),
    entry(baseDate, -6, {
      id: 'my-time-kumail-6',
      userId: 'team_kumail_abas',
      taskTitle: 'Mobile test synthesis',
      jobName: 'Mobile App Revamp',
      deliverableName: 'Usability Test',
      contextType: 'client',
      companyName: 'Appify',
      serviceTypeId: 'design',
      notes: 'Summarized test feedback into a clearer pattern list, including what should be fixed now and what can wait for the next product pass.',
      entryType: 'timer',
      startTime: '11:30',
      endTime: '13:00',
      duration_minutes: 90,
    }),
    entry(baseDate, -6, {
      id: 'my-time-marc-9',
      userId: 'team_marc_pitre',
      taskTitle: 'Quick client follow-up',
      jobName: '',
      deliverableName: '',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'pm',
      notes: 'Answered client questions about timing and clarified which performance fixes were already included in the current sprint.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 45,
    }),
    entry(baseDate, -7, {
      id: 'my-time-arthur-8',
      userId: 'team_arthur_iturres',
      taskTitle: 'Homepage component polish',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Homepage Refresh',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      serviceTypeId: 'development',
      notes: 'Adjusted the responsive component behavior and checked the page at the main review breakpoints before handing it back to design.',
      entryType: 'timer',
      startTime: '09:00',
      endTime: '11:15',
      duration_minutes: 135,
    }),
    entry(baseDate, -7, {
      id: 'my-time-kumail-7',
      userId: 'team_kumail_abas',
      taskTitle: 'Brand reference pass',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Brand Guidelines',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      serviceTypeId: 'design',
      notes: 'Reviewed references, tightened the language around visual direction, and flagged two examples that should be removed before client review.',
      entryType: 'timer',
      startTime: '13:00',
      endTime: '14:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -7, {
      id: 'my-time-marc-10',
      userId: 'team_marc_pitre',
      taskTitle: 'Internal planning cleanup',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Cleaned up the planning board and confirmed the reporting demo has enough internal work to test the Work Context filter.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 50,
    }),
    entry(baseDate, -1, {
      id: 'my-time-kumail-8',
      userId: 'team_kumail_abas',
      taskTitle: 'Quick Appify note',
      jobName: '',
      deliverableName: '',
      contextType: 'client',
      companyName: 'Appify',
      serviceTypeId: 'design',
      notes: 'Sent a short clarification about prototype copy and captured the next client question for follow-up.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 35,
    }),
    entry(baseDate, 0, {
      id: 'my-time-arthur-9',
      userId: 'team_arthur_iturres',
      taskTitle: 'Future Systems hotfix note',
      jobName: '',
      deliverableName: '',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'development',
      notes: 'Captured a quick hotfix note for the client support thread and tagged it for follow-up in the next engineering review.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 40,
    }),
    entry(baseDate, 0, {
      id: 'my-time-marc-11',
      userId: 'team_marc_pitre',
      taskTitle: 'Discovery interview synthesis',
      jobName: 'Civic Portal Discovery',
      deliverableName: 'Research Summary',
      contextType: 'client',
      companyName: 'CivicWorks',
      serviceTypeId: 'research',
      notes: 'Synthesized stakeholder interviews into a concise findings list, separated confirmed needs from assumptions, and marked the open questions that should be resolved before planning the next design pass.',
      entryType: 'timer',
      startTime: '11:00',
      endTime: '12:20',
      duration_minutes: 80,
    }),
    entry(baseDate, 0, {
      id: 'my-time-arthur-10',
      userId: 'team_arthur_iturres',
      taskTitle: 'Checkout QA replay',
      jobName: 'Harbor Retail Tune-Up',
      deliverableName: 'Regression QA',
      contextType: 'client',
      companyName: 'Harbor Retail',
      serviceTypeId: 'qa',
      notes: 'Replayed the checkout flow using the latest staging build, documented the remaining validation edge cases, and confirmed which issues were safe to move out of the launch blocker list.',
      entryType: 'timer',
      startTime: '13:15',
      endTime: '14:45',
      duration_minutes: 90,
    }),
    entry(baseDate, 0, {
      id: 'my-time-kumail-9',
      userId: 'team_kumail_abas',
      taskTitle: 'Content strategy outline',
      jobName: '',
      deliverableName: '',
      contextType: 'client',
      companyName: 'Fathom',
      serviceTypeId: 'strategy',
      notes: 'Outlined the next content recommendations and connected them back to search intent patterns so the client can review the plan without needing the full audit context.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 55,
    }),
    entry(baseDate, -1, {
      id: 'my-time-marc-12',
      userId: 'team_marc_pitre',
      taskTitle: 'Ops hiring scorecard',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'strategy',
      notes: 'Refined the internal hiring scorecard, clarified how review notes should be captured, and added examples so the team can compare candidates without overloading the process.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 65,
    }),
    entry(baseDate, -1, {
      id: 'my-time-arthur-11',
      userId: 'team_arthur_iturres',
      taskTitle: 'Mobile regression retest',
      jobName: 'Mobile App Revamp',
      deliverableName: 'Usability Test',
      contextType: 'client',
      companyName: 'Appify',
      serviceTypeId: 'qa',
      notes: 'Retested the mobile prototype after the interaction fixes, confirmed the reported tap-target issue was resolved, and captured one follow-up item for the next sprint.',
      entryType: 'timer',
      startTime: '09:15',
      endTime: '10:25',
      duration_minutes: 70,
    }),
    entry(baseDate, -1, {
      id: 'my-time-kumail-10',
      userId: 'team_kumail_abas',
      taskTitle: 'Audience interview coding',
      jobName: 'Civic Portal Discovery',
      deliverableName: 'Research Summary',
      contextType: 'client',
      companyName: 'CivicWorks',
      serviceTypeId: 'research',
      notes: 'Coded interview responses into recurring themes, noted where participant feedback conflicted, and prepared a short summary for the planning conversation.',
      entryType: 'timer',
      startTime: '15:00',
      endTime: '16:15',
      duration_minutes: 75,
    }),
    entry(baseDate, 0, {
      id: 'my-time-arthur-12',
      userId: 'team_arthur_iturres',
      taskTitle: 'Internal QA notes',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'qa',
      notes: 'Prepared internal QA notes for the reporting demo so grouped views include quality review work outside of client-backed jobs.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 50,
    }),
    entry(baseDate, -60, {
      id: 'my-time-marc-year-1',
      userId: 'team_marc_pitre',
      taskTitle: 'Retainer planning archive',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'pm',
      notes: 'Archived planning notes from the previous cycle so year-level reporting shows older internal work.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 65,
    }),
    entry(baseDate, -95, {
      id: 'my-time-arthur-year-1',
      userId: 'team_arthur_iturres',
      taskTitle: 'Legacy API review',
      jobName: 'Quantum Leap Website',
      deliverableName: 'API Integration',
      contextType: 'client',
      companyName: 'Future Systems',
      serviceTypeId: 'development',
      notes: 'Reviewed legacy API assumptions for the archived report sample.',
      entryType: 'timer',
      startTime: '10:00',
      endTime: '11:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -140, {
      id: 'my-time-kumail-year-1',
      userId: 'team_kumail_abas',
      taskTitle: 'Prior SEO benchmark',
      jobName: 'Fathom SEO Sprint',
      deliverableName: 'SEO Audit',
      contextType: 'client',
      companyName: 'Fathom',
      serviceTypeId: 'seo',
      notes: 'Captured benchmark notes for monthly aggregation testing.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 75,
    }),
    entry(baseDate, -190, {
      id: 'my-time-marc-year-2',
      userId: 'team_marc_pitre',
      taskTitle: 'Brand kickoff prep',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Logo Concepts',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      serviceTypeId: 'design',
      notes: 'Prepared early brand kickoff material for the annual reporting sample.',
      entryType: 'timer',
      startTime: '14:00',
      endTime: '15:15',
      duration_minutes: 75,
    }),
    entry(baseDate, -250, {
      id: 'my-time-arthur-year-2',
      userId: 'team_arthur_iturres',
      taskTitle: 'Older internal diagnostics',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      serviceTypeId: 'development',
      notes: 'Older internal diagnostics entry included so All Dates can show multiple monthly bars.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 55,
    }),
  ];
}
