function startOfLocalDay(value = new Date()) {
  return new Date(value.getFullYear(), value.getMonth(), value.getDate());
}

function shiftDays(base, days) {
  const next = startOfLocalDay(base);
  next.setDate(next.getDate() + days);
  return next;
}

function toLocalIso(date) {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function entry(baseDate, dayShift, payload) {
  return {
    date: toLocalIso(shiftDays(baseDate, dayShift)),
    ...payload,
  };
}

export function getMyTimeSeedEntries(now = new Date()) {
  const baseDate = startOfLocalDay(now);

  return [
    entry(baseDate, 0, {
      id: 'my-time-marc-1',
      userId: 'team_marc_pitre',
      taskTitle: 'Homepage QA sweep',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Launch QA',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      notes: 'Validated final responsive fixes before client review.',
      entryType: 'timer',
      startTime: '09:00',
      endTime: '10:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -1, {
      id: 'my-time-marc-2',
      userId: 'team_marc_pitre',
      taskTitle: 'Internal weekly planning',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      notes: 'Aligned priorities for My Time and task correction follow-up.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 45,
    }),
    entry(baseDate, -2, {
      id: 'my-time-marc-3',
      userId: 'team_marc_pitre',
      taskTitle: 'Perf tuning pass',
      jobName: 'Quantum Leap Website',
      deliverableName: 'Performance Tuning',
      contextType: 'client',
      companyName: 'Future Systems',
      notes: 'Closed image-loading regressions and cache test notes.',
      entryType: 'timer',
      startTime: '13:00',
      endTime: '15:15',
      duration_minutes: 135,
    }),
    entry(baseDate, -6, {
      id: 'my-time-marc-4',
      userId: 'team_marc_pitre',
      taskTitle: 'Stakeholder recap',
      jobName: 'Data Migration Strategy',
      deliverableName: 'Final Report Delivery',
      contextType: 'client',
      companyName: 'Legacy Corp',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 75,
    }),
    entry(baseDate, -5, {
      id: 'my-time-marc-locked-1',
      userId: 'team_marc_pitre',
      taskTitle: 'Archived launch wrap-up',
      jobName: 'Legacy Launch Retrospective',
      deliverableName: 'Archive Summary',
      contextType: 'client',
      companyName: 'Legacy Corp',
      notes: 'Historical entry locked after the parent work was archived.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 60,
      lockReason: 'Locked while parent work is archived.',
    }),
    entry(baseDate, -11, {
      id: 'my-time-marc-5',
      userId: 'team_marc_pitre',
      taskTitle: 'Change-order review',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Brand Guidelines',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      notes: 'Reviewed scope notes and consolidated open questions.',
      entryType: 'timer',
      startTime: '11:00',
      endTime: '12:30',
      duration_minutes: 90,
    }),
    entry(baseDate, -27, {
      id: 'my-time-marc-6',
      userId: 'team_marc_pitre',
      taskTitle: 'Template cleanup',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      notes: 'Reworked recurring checklist copy.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 60,
    }),
    entry(baseDate, 0, {
      id: 'my-time-arthur-1',
      userId: 'team_arthur_iturres',
      taskTitle: 'Deployment verification',
      jobName: 'Quantum Leap Website',
      deliverableName: 'Frontend Deployment',
      contextType: 'client',
      companyName: 'Future Systems',
      notes: 'Confirmed production bundle and smoke-tested launch flow.',
      entryType: 'timer',
      startTime: '10:00',
      endTime: '12:00',
      duration_minutes: 120,
    }),
    entry(baseDate, -1, {
      id: 'my-time-arthur-2',
      userId: 'team_arthur_iturres',
      taskTitle: 'Internal build diagnostics',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      notes: 'Investigated dev-build latency and noted next checks.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 90,
    }),
    entry(baseDate, -3, {
      id: 'my-time-arthur-3',
      userId: 'team_arthur_iturres',
      taskTitle: 'API handoff review',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'API Integration',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      notes: 'Reviewed edge cases with Andres before merge.',
      entryType: 'timer',
      startTime: '14:00',
      endTime: '16:30',
      duration_minutes: 150,
    }),
    entry(baseDate, -9, {
      id: 'my-time-arthur-4',
      userId: 'team_arthur_iturres',
      taskTitle: 'Footer refactor',
      jobName: 'NCBF Web Redesign',
      deliverableName: 'Homepage Refresh',
      contextType: 'client',
      companyName: 'National Cherry Blossom Festival',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 105,
    }),
    entry(baseDate, -34, {
      id: 'my-time-arthur-5',
      userId: 'team_arthur_iturres',
      taskTitle: 'Task system sync',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      notes: 'Checked alignment between Quick Tasks and Jobs task models.',
      entryType: 'timer',
      startTime: '15:00',
      endTime: '16:00',
      duration_minutes: 60,
    }),
    entry(baseDate, 0, {
      id: 'my-time-kumail-1',
      userId: 'team_kumail_abas',
      taskTitle: 'Proposal framing',
      jobName: 'Mobile App Revamp',
      deliverableName: 'Usability Test',
      contextType: 'client',
      companyName: 'Appify',
      notes: 'Drafted summary bullets for follow-up.',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 75,
    }),
    entry(baseDate, -2, {
      id: 'my-time-kumail-2',
      userId: 'team_kumail_abas',
      taskTitle: 'SEO audit review',
      jobName: 'Fathom SEO Sprint',
      deliverableName: 'SEO Audit',
      contextType: 'client',
      companyName: 'Fathom',
      notes: 'Validated deliverable notes and owner summary.',
      entryType: 'timer',
      startTime: '09:30',
      endTime: '11:00',
      duration_minutes: 90,
    }),
    entry(baseDate, -8, {
      id: 'my-time-kumail-3',
      userId: 'team_kumail_abas',
      taskTitle: 'Ops cleanup',
      jobName: '',
      deliverableName: '',
      contextType: 'internal',
      companyName: '',
      notes: '',
      entryType: 'manual',
      startTime: '',
      endTime: '',
      duration_minutes: 30,
    }),
    entry(baseDate, -31, {
      id: 'my-time-kumail-4',
      userId: 'team_kumail_abas',
      taskTitle: 'Estimate recap',
      jobName: 'Right Here Rebrand',
      deliverableName: 'Logo Concepts',
      contextType: 'client',
      companyName: 'Right Here Interactive',
      notes: 'Sent estimate summary after internal review.',
      entryType: 'timer',
      startTime: '12:00',
      endTime: '13:15',
      duration_minutes: 75,
    }),
  ];
}
